services:
  mongo:
    image: mongo:4.0.4
    container_name: mongo_shelf
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - mynet
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: shelf

networks:
  mynet:
    driver: bridge